### ISSUE TITLE
Minimax soccer game number of states

### ISSUE THREAD

**Issue by chrisplyn** [theevann/MinimaxQ-Learning#1]
Hi, 
I found you code very helpful to one of my projects.
I am trying to understand you code, can you explain a little bit when in the soccer game you set the 
number of states to be (boardW * boardH) * (boardW * boardH - 1) * 2?

Thanks!

**Comment by theevann** [comment]
Hi !
The number of states is the number of possible configurations of the world.
Since you have `boardW * boardH` positions on the board, and you got two players, there are :
 `boardW * boardH` positions for the first player to be on. Then, there remain only `boardW * boardH - 1` possible positions for the second player. Thus a total of  `T = (boardW * boardH) * (boardW * boardH - 1)`.
Then, you need to take into account that one of them possess the ball, thus multiply by two the number of possible states `T*2`. (ie, `T` states when player 1 possesses the ball, and `T` states when player 2 possesses it )

You may find my class report helpful. 
[COURDIER_PROJECT_REPORT.pdf](https://github.com/theevann/MinimaxQ-Learning/files/1505734/COURDIER_PROJECT_REPORT.pdf)

Hope this helps !
Happy you find my code helpful :)
